name: CI Docker Django

on:
  push:
    branches: [ "**" ]
    tags: [ "*" ]
  pull_request:

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/myapp
  WORKDIR: .   # tu peux laisser "." ; si tu sais le dossier exact, mets-le ici (ex: DjangoApp/DjangoApp/MyApp)

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug - lister les fichiers
        run: |
          pwd
          ls -la
          echo "---- repo tree (niveau 2) ----"
          find . -maxdepth 2 -type f | sort

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install flake8
        run: pip install --no-cache-dir flake8

      - name: Lint Python
        run: flake8 "${{ env.WORKDIR }}"

      - name: Localiser Dockerfile
        id: df
        shell: bash
        run: |
          set -e
          # 1) Candidat par défaut (WORKDIR/Dockerfile)
          CANDIDATE="${{ env.WORKDIR }}/Dockerfile"
          if [ -f "$CANDIDATE" ]; then
            DF="$CANDIDATE"
          else
            # 2) Recherche dans le repo
            DF="$(git ls-files | grep -E '(^|/)[Dd]ockerfile$' | head -n1 || true)"
          fi
          if [ -z "$DF" ]; then
            echo "Aucun Dockerfile trouvé dans le repo."; exit 1
          fi
          DIR="$(dirname "$DF")"
          echo "Dockerfile: $DF"
          echo "Contexte:  $DIR"
          echo "path=$DF" >> "$GITHUB_OUTPUT"
          echo "dir=$DIR" >> "$GITHUB_OUTPUT"

      - name: Lint Dockerfile (hadolint)
        run: |
          docker run --rm -v "${{ github.workspace }}:/repo" hadolint/hadolint hadolint "/repo/${{ steps.df.outputs.path }}"

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=short
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag

      - name: Localiser Dockerfile (mêmes règles)
        id: df
        shell: bash
        run: |
          CANDIDATE="${{ env.WORKDIR }}/Dockerfile"
          if [ -f "$CANDIDATE" ]; then DF="$CANDIDATE"; else DF="$(git ls-files | grep -E '(^|/)[Dd]ockerfile$' | head -n1 || true)"; fi
          [ -n "$DF" ] || { echo "Dockerfile introuvable"; exit 1; }
          DIR="$(dirname "$DF")"
          echo "path=$DF" >> "$GITHUB_OUTPUT"
          echo "dir=$DIR" >> "$GITHUB_OUTPUT"

      - name: Build (no push, load to local engine)
        uses: docker/build-push-action@v6
        with:
          context: ${{ steps.df.outputs.dir }}
          file:    ${{ steps.df.outputs.path }}
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Localiser Dockerfile (mêmes règles)
        id: df
        shell: bash
        run: |
          CANDIDATE="${{ env.WORKDIR }}/Dockerfile"
          if [ -f "$CANDIDATE" ]; then DF="$CANDIDATE"; else DF="$(git ls-files | grep -E '(^|/)[Dd]ockerfile$' | head -n1 || true)"; fi
          [ -n "$DF" ] || { echo "Dockerfile introuvable"; exit 1; }
          DIR="$(dirname "$DF")"
          echo "dir=$DIR" >> "$GITHUB_OUTPUT"

      - name: Rebuild pour scan (isoler le job)
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} "${{ steps.df.outputs.dir }}"

      - name: Trivy scan (fail on CRITICAL)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: table
          severity: MEDIUM,HIGH,CRITICAL
          ignore-unfixed: true
          vuln-type: 'os,library'
          exit-code: 1

  push:
    runs-on: ubuntu-latest
    needs: scan
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=short
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag

      - name: Localiser Dockerfile (mêmes règles)
        id: df
        shell: bash
        run: |
          CANDIDATE="${{ env.WORKDIR }}/Dockerfile"
          if [ -f "$CANDIDATE" ]; then DF="$CANDIDATE"; else DF="$(git ls-files | grep -E '(^|/)[Dd]ockerfile$' | head -n1 || true)"; fi
          [ -n "$DF" ] || { echo "Dockerfile introuvable"; exit 1; }
          DIR="$(dirname "$DF")"
          echo "path=$DF" >> "$GITHUB_OUTPUT"
          echo "dir=$DIR" >> "$GITHUB_OUTPUT"

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ${{ steps.df.outputs.dir }}
          file:    ${{ steps.df.outputs.path }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
